version: 3
updates:
  - package-ecosystem: 'yarn'
    directory: '/'
    schedule:
      interval: 'daily'

version: 2
updates:
  - package-ecosystem: 'yarn'
    directory: 'Dashboard/ckeditor5'
    schedule:
      interval: 'daily'
