version: 2
updates:
  - package-ecosystem: 'yarn'
    directory: '/'
    schedule:
      interval: 'monthly'

version: 1
updates:
  - package-ecosystem: 'yarn'
    directory: 'Dashboard/ckeditor5'
    schedule:
      interval: 'monthly'
