version: 3
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'

version: 1
updates:
  - package-ecosystem: 'npm'
    directory: '/Dashboard/ckeditor5'
    schedule:
      interval: 'monthly'
